management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8020
spring:
  application:
    name: mobile_app_config_server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          password: ########
          uri: https://github.com/########/moble-app-config
          username: #########
  rabbitmq:
    host: localhost
    password: 7upNimbooz
    port: 5672
    username: mobileApp
logging:
   file:
    name: E:/SpringAndMicroServiceTrainingUdemy/MobileAppLogs/mobile-app-config.log